# Crane-based derivation for the dnd-encounter-manager-server binary.
# Called from flake.nix with: import ./server.nix { inherit craneLib commonArgs pkgs; }
#
# The package output includes:
#   $out/bin/dnd-encounter-manager-server              — the server binary
#   $out/share/dnd-encounter-manager-server/frontend/  — compiled Elm frontend assets
#
# The NixOS module passes --frontend-path pointing at the share directory.
#
# Elm build: uses pkgs.elmPackages.fetchElmDeps with the elm-srcs.nix and
# registry.dat files generated by elm2nix.  All package fetching happens
# through individual fixed-output derivations, so the build is fully offline
# and hermetic.
#
# When elm.json dependency versions change, regenerate both files:
#   cd frontend
#   nix run 'github:NixOS/nixpkgs/25.11#elm2nix' -- convert 2>/dev/null > elm-srcs.nix
#   nix run 'github:NixOS/nixpkgs/25.11#elm2nix' -- snapshot
# then commit elm-srcs.nix and registry.dat.
{
  craneLib,
  commonArgs,
  pkgs,
}: let
  elmFrontend = pkgs.stdenv.mkDerivation {
    name = "dnd-encounter-manager-elm-frontend";
    src = ../../frontend;
    nativeBuildInputs = [pkgs.elmPackages.elm];

    configurePhase = pkgs.elmPackages.fetchElmDeps {
      elmPackages = import ../../frontend/elm-srcs.nix;
      elmVersion = "0.19.1";
      registryDat = ../../frontend/registry.dat;
    };

    buildPhase = ''
      elm make src/Main.elm --optimize --output elm.js
    '';

    installPhase = ''
      mkdir -p $out
      cp elm.js $out/
      cp public/style.css $out/
      # Stamp the script src with the Nix store hash so each build gets a
      # unique URL.  Browsers that cached /elm.js from a previous build will
      # fetch the new /elm.js?v=<hash> URL instead.
      STORE_HASH=$(basename $out | cut -d'-' -f1)
      sed "s|/elm.js|/elm.js?v=$STORE_HASH|g" public/index.html > $out/index.html
    '';
  };

  binary = craneLib.buildPackage (commonArgs
    // {
      pname = "dnd-encounter-manager-server";
      cargoExtraArgs = "-p dnd-encounter-manager-server";
    });
in
  pkgs.symlinkJoin {
    name = "dnd-encounter-manager-server";
    paths = [binary];
    postBuild = ''
      mkdir -p $out/share/dnd-encounter-manager-server
      ln -s ${elmFrontend} $out/share/dnd-encounter-manager-server/frontend
    '';
  }
